pipeline {
    agent any
    tools {nodejs "nodejs-20.2.0"}
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
          steps {
            echo 'Testing...'
            sh 'pwd'
            sh 'ls -la'
            sh 'snyk auth ${snyk-api-token-kk}'
            echo 'start snyk code test...'
            sh '/opt/jenkins/tools/snyk/snyk-linux code test'
            
            echo  'start snyk test'

            snykSecurity(
              snykInstallation: 'snyk@manual',
              // snykInstallation: 'snyk@latest',
              snykTokenId: 'snyk-api-token-kk',
              // place other optional parameters here, for example:
            )
          }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
